name: Build and Test Anomaly detection
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Build-ad:
    strategy:
      matrix:
        java: [8, 11, 14]
      fail-fast: false

    name: Build and Test Anomaly detection Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # anomaly-detection
      - name: Checkout AD
        uses: actions/checkout@v2

      - name: Assemble anomaly-detection
        run: |
          ./gradlew assemble -Dopensearch.version=1.3.2-SNAPSHOT
          echo "Creating ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT ..."
          mkdir -p ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT
          echo "Copying ./build/distributions/*.zip to ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT ..."
          ls ./build/distributions/
          cp ./build/distributions/*.zip ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT
          echo "Copied ./build/distributions/*.zip to ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT ..."
          ls ./src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.3.2.0-SNAPSHOT
      - name: Build and Run Tests
        run: |
          ./gradlew build -Dopensearch.version=1.3.2-SNAPSHOT
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal -Dopensearch.version=1.3.2-SNAPSHOT
      - name: Multi Nodes Integration Testing
        run: |
          ./gradlew integTest -PnumNodes=3