name: Build and Test Anomaly detection
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Build-ad-windows:
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Build and Test Anomaly Detection Plugin on Windows
    runs-on: windows-latest
    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # checkout Anomaly Detection
      - name: Checkout Anomaly Detection
        uses: actions/checkout@v2

      - name: Build and Run Tests
        run: |
          ./gradlew.bat build
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - name: Multi Nodes Integration Testing
        run: |
          ./gradlew integTest -PnumNodes=3
  Build-ad:
    strategy:
      matrix:
        java: [11,17]
      fail-fast: false

    name: Build and Test Anomaly detection Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # anomaly-detection
      - name: Checkout AD
        uses: actions/checkout@v2

      - name: Assemble anomaly-detection
        run: |
          ./gradlew assemble
      - name: Build and Run Tests
        run: |
          ./gradlew build -Dtest.logs=true
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - name: Multi Nodes Integration Testing
        run: |
          ./gradlew integTest -PnumNodes=3
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
